theme = "base16_transparent"

[editor]
mouse = true
line-number = "relative"
cursorline = true
color-modes = true
clipboard-provider = "wayland"

[editor.cursor-shape]
normal = "block"
select = "underline"
insert = "bar"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[keys.normal]
y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_before"
a = "insert_mode"
d = ["yank_main_selection_to_clipboard", "delete_selection_noyank"]

[keys.select]
y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_before"
d = ["yank_main_selection_to_clipboard", "delete_selection_noyank"]
